"""Deterministic generator for the v2.5 fictional sample CSVs.

Produces two files next to this script: ``fictional_month.csv`` (30 days, the
original -- regenerated byte-identical, six tests/oracles depend on it) and
``fictional_6month.csv`` (180 days with a baked-in weekend dip, the dataset the
M8 ML forecast spike runs on, plus the M9-planted service events -- scheduled
Maintenance stops and repair-length Faults, ADR-0009). Both are realistic
event-interval exports that carry every v2.5 column (recipe, speed_target,
speed_actual, planned, and the renamed stop_cause) and is engineered to load +
map + coerce **cleanly** under ``linelens`` (the M3 narrowest check: "loads +
maps cleanly", plan row 3).

Design decisions, and *why* each keeps the dataset clean against the rules in
``linelens/validation.py``:

* **One machine (M01).** ``timestamps_not_sorted`` checks file order for a
  single machine; two interleaved machines would trip it (and share start
  timestamps -> ``duplicate_timestamps``). One machine keeps the timeline a
  simple monotonic chain.
* **Continuous 24h back-to-back timeline, 3 shifts (A 06-14, B 14-22, C 22-06).**
  Each interval's ``timestamp_start`` equals the previous interval's
  ``timestamp_end``, so starts are strictly increasing, unique, and only
  *touch* (never overlap) -> no ``timestamps_not_sorted`` /
  ``duplicate_timestamps`` / ``overlapping_events``. No overnight gap -> no
  ``large_time_gap`` (which fires on a start-to-start diff > 10x the median).
* **Each calendar day is exactly 86400s by construction, starting at 00:00.**
  The day is split into four clock-ordered segments (C 00-06, A 06-14, B 14-22,
  C 22-24) whose budgets sum to 86400; ``_draw_duration`` caps both bounds at
  the remaining budget so each segment's last interval ends exactly on the
  segment wall. Midnight (24:00 = 00:00 next day) is therefore always an
  interval boundary -> **no interval straddles midnight**. This is the key to
  ``daily_duration_exceeds_86400``: that rule sums durations grouped by
  ``start.dt.floor("D")``, attributing a straddling interval's *full* duration
  to its start-date day, which would push a fully-covered day past 86400.
  Aligning every interval to its start-date day keeps each bucket at exactly
  86400. Continuous coverage also keeps total duration == span -> no
  ``total_duration_exceeds_span``.
* **Modest interval lengths** (<= ~50 min; the M9 repairs reach 120 min, still
  far under the gap factor) so no single start-to-start diff is anywhere near
  10x the median. ``verify`` asserts max_diff < 10 * median directly (the
  ``large_time_gap`` threshold).
* **States only Running / Stopped / Idle** (all in ``KNOWN_STATES``).
* **stop_cause blank on Running/Idle, one of the cause families on every Stopped**
  -> no ``stop_cause_while_running`` / ``stop_cause_missing_while_stopped``.
  The month file carries the original 7 families; the 6-month file adds
  ``Maintenance``, the 8th family locked in ``CONTEXT.md`` (M9, ADR-0009).
* **planned = True only on Changeover and Maintenance.** Changeover (recipe
  switch) and Maintenance (scheduled service stop) are the inherently
  *scheduled* families; the other six (Fault, External, Starvation, Buildup,
  Operator, Supplies) are unplanned failures and carry planned=False. M4
  excludes planned stops from Availability. Maintenance appears only on the
  6-month profile (MAINTENANCE_ON, see the planting note below); the month
  file keeps Changeover as its only planned cause, byte-identical.
* **duration_seconds is an integer and exactly end - start** -> no
  ``duration_inconsistent``; ``good_count = round(speed_actual * duration/3600)``
  for Running rows; ~0.35-0.45% rejects (Quality ~99.6%); 0 counts when not
  running.
* **A gentle month-long drift** in performance, stop load, and reject rate so
  daily OEE has a real trend for M7's banded forecast.

Reproducibility: a fixed ``random`` seed; no wall-clock dependency. Re-run to
regenerate the exact same CSV.

    .venv\\Scripts\\python.exe sample_data\\generate_month.py

Note on the plan's "~16 scheduled hrs/day": that proposal is pending user
sign-off. A 16h-on / 8h-off schedule would leave an 8h overnight *gap* in the
export (firing ``large_time_gap`` ~30x) or require an 8h planned stop labelled
with a cause family it doesn't fit. The 24h continuous operation here stays
within the plan's "2-3 shifts" spirit and yields a truly clean dataset; the
actual run/stop/idle breakdown is reported at generation time. Flagged for the
user.
"""
from __future__ import annotations

import csv
import math
import random
import statistics
from datetime import datetime, timedelta
from pathlib import Path

# --- determinism ----------------------------------------------------------
SEED = 20260623
rng = random.Random(SEED)

# --- schedule -------------------------------------------------------------
# DAYS / WEEKLY_ON are set per output profile by run_profile() in main(). The
# 30-day month keeps its original values (DAYS=30, WEEKLY_ON=False) so it
# regenerates byte-identical -- six tests/oracles consume it.
DAYS = 30
WEEKLY_ON = False
START = datetime(2026, 6, 23, 0, 0, 0)  # day 0; long runs just extend later
SECONDS_PER_DAY = 24 * 3600

MACHINE = "M01"

# Shifts within a calendar day, in clock order. Shift C is split across
# midnight: the tail of the *previous* calendar day's C shift runs 00:00-06:00
# on this day (segment "C_prev"), then A 06-14, B 14-22, C 22-24 (segment "C").
# The four segments sum to exactly 86400s and their walls are all on the hour,
# so midnight is always an interval boundary -> no interval straddles a day.
# (label, hours_in_day, seconds) for the segments a single day emits, in order.
DAY_SEGMENTS = (
    ("C", 0, 6 * 3600),     # 00:00-06:00: tail of the overnight C shift
    ("A", 6, 8 * 3600),     # 06:00-14:00
    ("B", 14, 8 * 3600),    # 14:00-22:00
    ("C", 22, 2 * 3600),    # 22:00-24:00: head of the overnight C shift
)

# Two recipes grounded in the real export (Data/datatypes to add.txt:
# RCPrn "Lampone Zero 560ml", SpeedTarget 2200). Second recipe is plausible.
RECIPES = {
    "Lampone Zero 560ml": 2200,   # bottles/hour target
    "Arancia Rossa 500ml": 2400,
}
RECIPE_ORDER = list(RECIPES)

# The 7 stop-cause families locked in CONTEXT.md, plus Maintenance (M9,
# ADR-0009): the 8th family, always planned — the labeled service event the
# maintenance forecast learns from. Changeover is planned (scheduled recipe
# switch); the six others are unplanned failures.
PLANNED_CAUSE = "Changeover"
MAINTENANCE_CAUSE = "Maintenance"  # planned service stop (ADR-0009)
PLANNED_CAUSES = (PLANNED_CAUSE, MAINTENANCE_CAUSE)
UNPLANNED_CAUSES = ("Fault", "External", "Starvation", "Buildup", "Operator", "Supplies")

# Pareto weighting for unplanned stops: Starvation >> External > Buildup >
# Fault > Operator > Supplies (plan lines 53-54). Relative weights. The two
# tail causes (Operator / Supplies) are given a 2:1 ratio so their ordering is
# robust to sampling variance at the month's small counts, not flipped by a
# single draw.
UNPLANNED_WEIGHTS = {
    "Starvation": 40,
    "External": 22,
    "Buildup": 15,
    "Fault": 10,
    "Operator": 8,
    "Supplies": 4,
}

# Per-interval-type duration ranges in seconds (min, max). Kept modest so no
# start-to-start diff approaches 10x the median (large_time_gap). The drift
# multiplier is applied to unplanned-stop maxes only (see _draw_duration).
#
# Unplanned-cause ranges are deliberately *comparable* (same 2-15 min band)
# so the Pareto ranking is driven by UNPLANNED_WEIGHTS (the count of stops),
# not by one cause happening to have longer intervals. The plan's ranking is
# in bottles-lost = downtime seconds, and seconds = count x mean duration;
# equalizing the mean lets the weight alone set the rank. (Fault gets a
# slightly wider top end to read as "the rare long breakdown".)
DURATION_RANGE = {
    "Running": (1200, 3600),        # 20-60 min producing
    "Idle": (300, 1200),            # 5-20 min waiting/buffering
    PLANNED_CAUSE: (900, 2400),     # 15-40 min recipe changeover
    MAINTENANCE_CAUSE: (1800, 4500),  # 30-75 min scheduled service stop
    "Starvation": (120, 900),       # 2-15 min upstream empty
    "Buildup": (120, 900),          # 2-15 min downstream full
    "External": (120, 900),         # 2-15 min power/facility
    "Fault": (120, 900),            # 2-15 min machine fault
    "Operator": (120, 900),         # 2-15 min operator action
    "Supplies": (120, 900),         # 2-15 min consumables
}

# --- predictive-maintenance planting (M9, ADR-0009) -------------------------
# Gated by MAINTENANCE_ON (per output profile, like WEEKLY_ON): off for the
# 30-day month (byte-identical), on for the 180-day file. Two signals:
# * Scheduled service stops (Maintenance, always planned) every
#   SERVICE_PERIOD_DAYS, planted at the 06:00 shift-A start like a Changeover.
# * Repair-length Faults (corrective service, "it broke and they fixed it"):
#   a rare long Fault every REPAIR_PERIOD_DAYS, planted mid-shift-B. 45-120 min
#   is far above the drifted routine-fault ceiling (900s x 1.2 = 1080s), so the
#   repair tail separates cleanly — the gap the learned threshold (P2) finds.
# Both keep every verify() invariant: they consume shift budget exactly, so the
# timeline stays back-to-back and each day sums to 86400s; a 2h repair is well
# under the 10x-median large_time_gap factor.
#
# Why weekly service: the M8 forecast features are lag1/2/7, roll7, dow, t. A
# 14- or 21-day cadence lands on *alternating* Tuesdays, which dow/lag7 cannot
# represent — the dip reads as noise, the trees chase it, and the beats-linear
# gate (tests/test_forecast_ml.py) breaks. A 7-day cadence makes EVERY Tuesday
# a service day: dow + lag7 determine it exactly, the model learns it like the
# weekend dip, and the gate passes on structure, not luck. Repairs stay on a
# 23-day scatter — genuinely random, as real corrective service is.
#
# Why a dedicated service rng: the beats-linear gate's pre-M9 margin was thin
# (~300 bottles), so re-rolling the shared rng sequence (which any inserted
# draw does) re-rolls the entire noise realization and flips the gate on luck.
# Drawing service/repair durations from a SEPARATE stream keeps every base
# draw identical to the pre-M9 file — the only delta is the intended one:
# service stop time replacing run time on service days.
SERVICE_PERIOD_DAYS = 7             # weekly service (every Tuesday), ~25 stops/180d
REPAIR_PERIOD_DAYS = 23             # ~8 repairs over 180 days
REPAIR_OFFSET = 10                  # first repair on day 10 (not day 0)
REPAIR_RANGE = (2700, 7200)         # 45-120 min corrective-service Fault
MAINTENANCE_ON = False
_service_rng = random.Random(0)     # re-seeded per profile in run_profile()


def _draw_service_duration(kind_range: tuple[int, int], remaining: int) -> int:
    """A service/repair duration from the dedicated service stream (see above),
    capped at the remaining shift budget like _draw_duration."""
    lo, hi = kind_range
    hi = min(hi, remaining)
    return _service_rng.randint(min(lo, hi), hi)

# Interval-type weights within a shift. Running dominates; Idle is a small
# filler; Stop is split across the 6 unplanned causes by UNPLANNED_WEIGHTS.
# Changeovers are inserted explicitly at recipe switches, not sampled here.
RUNNING_WEIGHT = 70.0
IDLE_WEIGHT = 5.0
STOP_WEIGHT = 25.0

# When a shift has less than this left, fill the tail with an Idle of exactly
# the remainder (no sliver intervals, no overflow past the 8h wall).
TAIL_IDLE_FLOOR = 300

LARGE_GAP_FACTOR = 10.0  # mirrors validation.GAP_FACTOR

# --- weekly rhythm (the ML signal) ---------------------------------------
# A weekend dip on speed_actual: lighter Friday, real drops Saturday/Sunday.
# This is the recurring pattern a flat trend line cannot see and a feature-based
# forecaster (linear-on-features / gradient boosting) can -- the whole reason to
# move off the bare trend projection. Applied to speed_actual ONLY (durations and
# the timeline are untouched) so every verify() invariant still holds. Gated by
# WEEKLY_ON: off for the 30-day month (keeps it byte-identical for the oracles),
# on for the long ML dataset.
_WEEKLY_MULT = {0: 1.00, 1: 1.00, 2: 1.00, 3: 1.00, 4: 0.97, 5: 0.90, 6: 0.84}


def _weekly_factor(day: int) -> float:
    if not WEEKLY_ON:
        return 1.0
    return _WEEKLY_MULT[(START + timedelta(days=day)).weekday()]


# --- drift across the month (gentle, so OEE has a real trend) -------------
# progress in [0, 1] over the period. Performance sags then recovers; stop load
# and reject rate creep up slightly. All gentle enough to stay realistic.


def performance_factor(day: int) -> float:
    progress = day / (DAYS - 1)
    base = 0.93 - 0.05 * progress + 0.03 * math.sin(progress * 2.0 * math.pi)
    return base * _weekly_factor(day)


def stop_load_factor(day: int) -> float:
    # up to +20% stop duration by month-end -> Availability drifts down
    return 1.0 + 0.20 * (day / (DAYS - 1))


def reject_rate(day: int) -> float:
    return 0.0035 + 0.0010 * (day / (DAYS - 1))  # 0.35% -> 0.45%


# --- generation -----------------------------------------------------------

COLUMNS = [
    "machine_id", "timestamp_start", "timestamp_end", "state", "stop_cause",
    "shift", "recipe", "speed_target", "speed_actual", "duration_seconds",
    "good_count", "reject_count", "planned",
]

_FMT = "%Y-%m-%d %H:%M:%S"


def _draw_duration(kind: str, remaining: int, day: int) -> int:
    """A duration for `kind` that never exceeds `remaining`.

    Both bounds are capped at the remaining budget so the last interval of a
    shift consumes the remainder exactly (shift = exactly 8h, no timeline
    drift). Unplanned-stop maxes are scaled by the day's stop-load drift.
    """
    lo, hi = DURATION_RANGE[kind]
    if kind in UNPLANNED_CAUSES:
        hi = int(hi * stop_load_factor(day))
    hi = min(hi, remaining)
    lo = min(lo, hi)
    lo = max(lo, 1)
    return rng.randint(lo, hi)


def _pick_unplanned_cause() -> str:
    return rng.choices(
        list(UNPLANNED_WEIGHTS), weights=list(UNPLANNED_WEIGHTS.values())
    )[0]


def _pick_interval_type() -> str:
    return rng.choices(
        ["Running", "Idle", "Stop"],
        weights=[RUNNING_WEIGHT, IDLE_WEIGHT, STOP_WEIGHT],
    )[0]


def _recipes_for_day(day: int) -> dict[str, str]:
    """A recipe per shift (A/B/C) for `day`, guaranteeing >=1 recipe switch so
    a Changeover occurs. Shift A alternates by day; shift B always flips from
    A's recipe; the overnight C shift usually holds B's recipe but may flip.

    The C shift spans midnight; its recipe is decided once per day and applies
    to both the 22-24 head on `day` and the 00-06 tail on `day+1`. That
    continuation is handled in generate() by carrying `current_recipe` across
    the day boundary (no changeover at midnight -- the overnight shift simply
    keeps running). Returns {shift_label: recipe}.
    """
    a = RECIPE_ORDER[day % 2]
    b = RECIPE_ORDER[1 - RECIPE_ORDER.index(a)]
    # C holds B's recipe ~70% of the time; otherwise flips, for variety.
    c = b if rng.random() < 0.7 else RECIPE_ORDER[1 - RECIPE_ORDER.index(b)]
    return {"A": a, "B": b, "C": c}


def _emit(rows, start: datetime, state: str, cause: str, shift: str,
          recipe: str, target: int, speed_actual: int, duration: int) -> datetime:
    end = start + timedelta(seconds=duration)
    if state == "Running":
        good = round(speed_actual * duration / 3600)
        reject = max(0, round(good * reject_rate(_day_index(start)) * (0.8 + 0.4 * rng.random())))
    else:
        good, reject = 0, 0
    rows.append({
        "machine_id": MACHINE,
        "timestamp_start": start.strftime(_FMT),
        "timestamp_end": end.strftime(_FMT),
        "state": state,
        "stop_cause": cause,        # "" for Running/Idle
        "shift": shift,
        "recipe": recipe,
        "speed_target": target,
        "speed_actual": speed_actual,
        "duration_seconds": duration,
        "good_count": good,
        "reject_count": reject,
        "planned": "True" if cause in PLANNED_CAUSES else "False",
    })
    return end


def _day_index(ts: datetime) -> int:
    return (ts - START).days


def _fill_shift(rows, cursor: datetime, shift: str, recipe: str, target: int,
                perf: float, day: int, budget: int) -> datetime:
    """Emit exactly `budget` seconds of intervals for one shift."""
    remaining = budget
    while remaining >= 1:
        if remaining < TAIL_IDLE_FLOOR:
            cursor = _emit(rows, cursor, "Idle", "", shift, recipe, target, 0, remaining)
            remaining = 0
            continue
        kind = _pick_interval_type()
        if kind == "Running":
            dur = _draw_duration("Running", remaining, day)
            speed_actual = max(0, int(round(target * perf * (1.0 + 0.04 * (rng.random() - 0.5)))))
            cursor = _emit(rows, cursor, "Running", "", shift, recipe, target, speed_actual, dur)
        elif kind == "Idle":
            dur = _draw_duration("Idle", remaining, day)
            cursor = _emit(rows, cursor, "Idle", "", shift, recipe, target, 0, dur)
        else:  # Stop -> an unplanned cause
            cause = _pick_unplanned_cause()
            dur = _draw_duration(cause, remaining, day)
            cursor = _emit(rows, cursor, "Stopped", cause, shift, recipe, target, 0, dur)
        remaining -= dur
    return cursor


def _is_service_day(day: int) -> bool:
    """A scheduled Maintenance stop lands at this day's shift-A start (M9)."""
    return MAINTENANCE_ON and day > 0 and day % SERVICE_PERIOD_DAYS == 0


def _is_repair_day(day: int) -> bool:
    """A repair-length Fault lands mid-shift-B this day (M9)."""
    return MAINTENANCE_ON and day % REPAIR_PERIOD_DAYS == REPAIR_OFFSET


def generate() -> list[dict]:
    rows: list[dict] = []
    cursor = START
    # `current_recipe` is the recipe the machine is actually running as of
    # `cursor`. It carries across midnight so the overnight C shift is one
    # continuous run (no spurious changeover at 00:00) and across the A/B
    # handoffs (a changeover is emitted only when the recipe actually changes).
    current_recipe = RECIPE_ORDER[0]
    for day in range(DAYS):
        perf = performance_factor(day)
        day_recipes = _recipes_for_day(day)
        for seg_label, _hours, budget in DAY_SEGMENTS:
            # Which shift owns this segment's recipe? The 00-06 "C" segment is
            # the tail of YESTERDAY's overnight C shift, so it keeps
            # `current_recipe` (set by yesterday's 22-24 segment) and does NOT
            # re-decide a recipe. All other segments take the day's recipe for
            # their shift label.
            if seg_label == "C" and _hours == 0:
                seg_recipe = current_recipe  # overnight continuation
            else:
                seg_recipe = day_recipes[seg_label]
            target = RECIPES[seg_recipe]
            if seg_recipe != current_recipe:  # Changeover at the segment's start
                dur = _draw_duration(PLANNED_CAUSE, budget, day)
                cursor = _emit(rows, cursor, "Stopped", PLANNED_CAUSE, seg_label,
                               seg_recipe, target, 0, dur)
                budget -= dur
            current_recipe = seg_recipe
            if seg_label == "A" and _is_service_day(day):
                # M9: scheduled service stop at the 06:00 shift start (ADR-0009).
                dur = _draw_service_duration(DURATION_RANGE[MAINTENANCE_CAUSE], budget)
                cursor = _emit(rows, cursor, "Stopped", MAINTENANCE_CAUSE,
                               seg_label, seg_recipe, target, 0, dur)
                budget -= dur
            if seg_label == "B" and _is_repair_day(day):
                # M9: corrective service mid-shift — split the segment around a
                # repair-length Fault (ADR-0009: repairs reset the counter too).
                first = budget // 3
                cursor = _fill_shift(rows, cursor, seg_label, seg_recipe, target,
                                     perf, day, first)
                budget -= first
                dur = _draw_service_duration(REPAIR_RANGE, budget)
                cursor = _emit(rows, cursor, "Stopped", "Fault", seg_label,
                               seg_recipe, target, 0, dur)
                budget -= dur
            cursor = _fill_shift(rows, cursor, seg_label, seg_recipe, target,
                                 perf, day, budget)
    return rows


# --- self-verification (asserts the "clean" invariants during generation) --

def verify(rows: list[dict]) -> None:
    assert rows, "no rows generated"
    starts = [datetime.strptime(r["timestamp_start"], _FMT) for r in rows]
    ends = [datetime.strptime(r["timestamp_end"], _FMT) for r in rows]
    diffs: list[float] = []
    for i in range(len(rows)):
        dur = (ends[i] - starts[i]).total_seconds()
        assert int(dur) == int(rows[i]["duration_seconds"]), f"duration mismatch row {i+2}"
        assert dur > 0, f"non-positive duration row {i+2}"
        if i > 0:
            assert starts[i] > starts[i - 1], f"start not strictly increasing row {i+2}"
            assert starts[i] == ends[i - 1], f"timeline not back-to-back row {i+2}"
            diffs.append((starts[i] - starts[i - 1]).total_seconds())
    # large_time_gap invariant: max start-to-start diff < 10x the median
    median = statistics.median(diffs)
    threshold = median * LARGE_GAP_FACTOR
    worst = max(diffs)
    assert worst < threshold, f"large_gap risk: max diff {worst:.0f}s >= {threshold:.0f}s (10x median {median:.0f}s)"
    # state / stop_cause / planned coupling
    for i, r in enumerate(rows):
        if r["state"] == "Running":
            assert r["stop_cause"] == "", f"cause while running row {i+2}"
            assert r["planned"] == "False"
            assert r["speed_actual"] > 0 and r["good_count"] > 0
        elif r["state"] == "Idle":
            assert r["stop_cause"] == ""
            assert r["planned"] == "False"
            assert r["speed_actual"] == 0 and r["good_count"] == 0
        elif r["state"] == "Stopped":
            assert r["stop_cause"] in UNPLANNED_CAUSES + PLANNED_CAUSES, f"bad cause row {i+2}"
            assert r["planned"] == ("True" if r["stop_cause"] in PLANNED_CAUSES else "False")
            assert r["speed_actual"] == 0 and r["good_count"] == 0
        else:
            raise AssertionError(f"unknown state {r['state']!r} row {i+2}")
    # good_count == speed_actual * duration / 3600 (rounded) for running rows
    for i, r in enumerate(rows):
        if r["state"] == "Running":
            expect = round(r["speed_actual"] * r["duration_seconds"] / 3600)
            assert r["good_count"] == expect, f"good_count formula row {i+2}: {r['good_count']} != {expect}"
    # daily duration <= 86400 (continuous coverage; first/last day partial)
    by_day: dict[str, int] = {}
    for r in rows:
        d = r["timestamp_start"][:10]
        by_day[d] = by_day.get(d, 0) + r["duration_seconds"]
    for d, total in by_day.items():
        assert total <= 86400, f"day {d} sums to {total}s > 86400"


def summarize(rows: list[dict]) -> str:
    n = len(rows)
    span = (datetime.strptime(rows[-1]["timestamp_end"], _FMT)
            - datetime.strptime(rows[0]["timestamp_start"], _FMT))
    by_state: dict[str, int] = {}
    by_cause: dict[str, int] = {}
    planned_secs = 0
    good = reject = 0
    for r in rows:
        by_state[r["state"]] = by_state.get(r["state"], 0) + r["duration_seconds"]
        if r["stop_cause"]:
            by_cause[r["stop_cause"]] = by_cause.get(r["stop_cause"], 0) + r["duration_seconds"]
            if r["planned"] == "True":
                planned_secs += r["duration_seconds"]
        good += r["good_count"]
        reject += r["reject_count"]
    total_secs = sum(r["duration_seconds"] for r in rows)
    run_secs = by_state.get("Running", 0)
    unplanned_secs = sum(v for k, v in by_cause.items() if k not in PLANNED_CAUSES)
    avail = run_secs / (run_secs + unplanned_secs) if (run_secs + unplanned_secs) else 0
    perf_num = sum(r["speed_actual"] * r["duration_seconds"] for r in rows if r["state"] == "Running")
    perf_den = sum(r["speed_target"] * r["duration_seconds"] for r in rows if r["state"] == "Running")
    perf = perf_num / perf_den if perf_den else 0
    qual = good / (good + reject) if (good + reject) else 0
    oee = avail * perf * qual
    lines = [
        f"rows: {n}",
        f"span: {rows[0]['timestamp_start']} -> {rows[-1]['timestamp_end']} ({span.days}d)",
        f"state seconds: {by_state}",
        f"stop-cause seconds (Pareto, descending):",
    ]
    for cause, secs in sorted(by_cause.items(), key=lambda kv: -kv[1]):
        lines.append(f"    {cause:<12} {secs:>8}s  ({secs/total_secs*100:5.1f}%)  planned={'yes' if cause in PLANNED_CAUSES else 'no '}")
    lines.append(f"planned stop seconds: {planned_secs}s ({planned_secs/total_secs*100:.1f}% of total)")
    lines.append(f"good={good:,}  reject={reject:,}  quality={qual*100:.2f}%")
    lines.append(f"Availability={avail*100:.1f}%  Performance={perf*100:.1f}%  Quality={qual*100:.1f}%  OEE={oee*100:.1f}%")
    return "\n".join(lines)


def run_profile(days: int, weekly: bool, out_name: str, seed: int,
                maintenance: bool = False) -> None:
    """Generate one output: set the period + weekly/maintenance switches,
    re-seed, generate, verify, write. Re-seeding per profile makes each file
    independently reproducible and keeps the month byte-identical to its
    pre-parameterization form (same SEED, WEEKLY_ON=False, MAINTENANCE_ON=False,
    DAYS=30, same START)."""
    global DAYS, WEEKLY_ON, MAINTENANCE_ON, rng, _service_rng
    DAYS = days
    WEEKLY_ON = weekly
    MAINTENANCE_ON = maintenance
    rng = random.Random(seed)
    _service_rng = random.Random(seed + 7919)  # dedicated service stream (see M9 note)
    rows = generate()
    verify(rows)
    out = Path(__file__).parent / out_name
    with out.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=COLUMNS)
        writer.writeheader()
        writer.writerows(rows)
    print(f"wrote {out} ({len(rows)} rows, {len(COLUMNS)} columns, "
          f"{days} days, weekly={'on' if weekly else 'off'}, "
          f"maintenance={'on' if maintenance else 'off'})")
    print()
    print(summarize(rows))
    print()


def main() -> None:
    # The 30-day month is regenerated byte-identical (oracles depend on it);
    # the 180-day (~6 mo) file adds the weekly dip the ML spike needs and the
    # planted service events (Maintenance stops + repair-length Faults) the M9
    # maintenance forecast learns from (ADR-0009).
    run_profile(days=30, weekly=False, out_name="fictional_month.csv", seed=SEED)
    run_profile(days=180, weekly=True, out_name="fictional_6month.csv",
                seed=SEED + 1, maintenance=True)


if __name__ == "__main__":
    main()
